services:
  opssig:
    build:
      context: .
      dockerfile: docker/${ENV}/Dockerfile
      args:
        ENV: ${ENV}
        SPARK_SQL_WAREHOUSE_DIR: ${SPARK_SQL_WAREHOUSE_DIR}
        OPSSIG_VERSION: ${OPSSIG_VERSION}
        DELTA_PACKAGE_VERSION: ${DELTA_PACKAGE_VERSION}
        DELTA_SPARK_VERSION: ${DELTA_SPARK_VERSION}
        DELTALAKE_VERSION: ${DELTALAKE_VERSION}
        JUPYTERLAB_VERSION: ${JUPYTERLAB_VERSION}
        PANDAS_VERSION: ${PANDAS_VERSION}
        ROAPI_VERSION: ${ROAPI_VERSION}
        MATPLOTLIB_VERSION: ${MATPLOTLIB_VERSION}
        PYTEST_VERSION: ${PYTEST_VERSION}
    image: opssig_${ENV}v${OPSSIG_VERSION}
    container_name: opssig-${ENV}v${OPSSIG_VERSION}
    environment:
      - ENV=${ENV}
      - OPSSIG_VERSION=${OPSSIG_VERSION}
      - DELTA_PACKAGE_VERSION=${DELTA_PACKAGE_VERSION}
      - DELTA_SPARK_VERSION=${DELTA_SPARK_VERSION}
      - DELTALAKE_VERSION=${DELTALAKE_VERSION}
      - JUPYTERLAB_VERSION=${JUPYTERLAB_VERSION}
      - PANDAS_VERSION=${PANDAS_VERSION}
      - MATPLOTLIB_VERSION=${MATPLOTLIB_VERSION}
      - ROAPI_VERSION=${ROAPI_VERSION}
      - PYTEST_VERSION=${PYTEST_VERSION}
    ports:
      - "8888:8888"
      - "4040-4045:4040-4045"
